# CauferoAppStarter AI Training Documentation
## Dashboard Development (WebViewer + ChartJS)

> Purpose  
> Train an AI Agent to reliably generate a complete dashboard page inside CauferoAppStarter using the established pattern: **Theme-driven CSS + HTML blocks + JavaScript blocks + Page assembly**.  
> The agent must output FileMaker script steps (Set Variable, Perform Script, etc.) and the HTML/CSS/JS payloads in a way that matches CauferoAppStarter conventions.

---

## 1) Dashboard Definition in CauferoAppStarter

A **Dashboard** in CauferoAppStarter is a **single HTML page** rendered inside a WebViewer / WebDirect context, composed from:

1. **Theme-driven CSS**  
2. **HTML blocks** (cards, charts, tables, timelines, etc.)  
3. **JavaScript blocks** (ChartJS initializations + small UI animations)  
4. **External JS preload** (ChartJS library or any dashboard JS library stored in a table)  
5. **Final Page HTML** stored in `$$Page`

The whole dashboard is generated by a FileMaker script that:
- sets `$$App Section = "Dashboard"`
- pulls reusable JS payload from a table via ExecuteSQL (example: `ChartJS::JS`)
- builds CSS variables based on `$$Theme`
- builds multiple HTML blocks into `$HTML`
- builds multiple JS blocks into `$Scripts`
- assembles `$$Page` as a full HTML document and refreshes the window

---

## 2) Hard Requirements (AI Must Follow)

### 2.1 Use the Standard Variable Names

The AI must use these variable scopes as a baseline:

- `$$App Section`  
- `$$Theme`  
- `$Dashboard JS`  
- `$Styles`  
- `$HTML`  
- `$Scripts`  
- `$$Page`  

If additional variables are needed, keep them consistent and descriptive:
- `$Pie Chart HTML`, `$Pie Chart JS`, `$KPI Card Colours`, etc.

### 2.2 Use the Standard Build Order

The AI must generate in this exact order:

1. **Context**
2. **External JS preload** (ExecuteSQL or other retrieval)
3. **Theme variables (colors, sizes, chart settings)**
4. **CSS (including KPI nth-child mapping)**
5. **Call shared Dashboard CSS script**
6. **HTML blocks**
7. **JS blocks**
8. **Assemble `$$Page`**
9. **Pause / refresh for WebDirect**

### 2.3 Keep Chart IDs and JS Selectors Perfectly Matched

If the HTML defines:
- `<canvas id='pieChart'></canvas>`

Then the JS must reference:
- `document.getElementById('pieChart')`

Zero mismatches allowed.

### 2.4 Use Self-Invoking JS Wrappers Per Chart

Dashboard JS blocks must use a safe scope, example:

~~~js
(function () {
  const ctx = document.getElementById('pieChart').getContext('2d');
  new Chart(ctx, {...});
})();
~~~

This avoids variable collisions when multiple charts exist.

### 2.5 Theme Must Drive Colors Everywhere

The AI must generate theme-mapped values for:
- KPI card backgrounds
- Pie chart colors
- Line graph dataset colors
- Axis colors
- Grid colors
- Bar chart colors
- Stacked bars colors
- Gauge colors
- Progress circle stroke

If the theme is unknown, provide a default palette.

---

## 3) Data Sources and Retrieval Pattern

### 3.1 External ChartJS / Dashboard JS Retrieval via ExecuteSQL

Dashboard JS libraries or shared JS can be stored in a table (example: `ChartJS`) and loaded like:

~~~filemaker
Set Variable [ $Dashboard JS ; 
  Value: Let ( 
    [
      sql = "Select JS From ChartJS" ;
      fieldseparator = "xxxxxxxxxx" ;
      rowseparator = "yyyyyyyyyy" ;
      result = ExecuteSQL ( sql ; fieldseparator ; rowseparator )
    ] ;
    result
  )
]
~~~

#### Notes for the AI
- `fieldseparator` and `rowseparator` are hard-coded tokens used to avoid collisions in retrieved text.
- If multiple rows are returned, the agent must decide whether:
  - to use the first row only, or
  - to concatenate rows, or
  - to filter by name/version.
- If the table is empty, the agent must still build the dashboard page, but charts may not render unless ChartJS is otherwise included.

### 3.2 Dashboard Data Strategy

Dashboards can use one of these data strategies:

1. **Static demo data** (as in the sample code)  
2. **FileMaker data injected into JS** using:
   - `JSONSetElement()` to create a JSON payload
   - `Substitute()` to inject JSON into HTML/JS template
3. **AJAX bridge** (advanced)  
   - A JavaScript call that triggers FileMaker script via URL scheme or `Perform Script` bridge pattern (implementation depends on platform)

For AI training, default to:
- **Static demo data** for initial dashboard templates
- Provide clear placeholders where real data gets injected

---

## 4) Theme Mapping System

### 4.1 Themes Are Selected via `$$Theme`

The dashboard script reads the global theme:

- `$$Theme = "AquaView"`
- `$$Theme = "Aurora"`
- `$$Theme = "ContrastCard"`
- `$$Theme = "Dokondo"`
- etc.

### 4.2 Theme Variables the AI Must Produce

The AI must generate these variables (even if simplified):

- `$KPI Card Colours` (List)
- `$PieBorderWidth`
- `$PieColours`
- `$Line Graph Colours`
- `$AxisColours _X`
- `$GridColours`
- `$Bar Chart Colours`
- `$Stacked Bars Colours`
- `$Gauge Colours`
- `$Progress Circle Stroke`

#### Example: KPI Card Colors as a List

~~~filemaker
Set Variable [ $KPI Card Colours ;
  Value: Case ( 
    $$Theme = "AquaView" ;
      List ( "#26A69A" ; "#4CAF50" ; "#FF9800" ; "#FF7043" ; "#9C27B0" ; "#00BCD4" ) ;
    $$Theme = "Aurora" ;
      List ( "#EF476F" ; "#06D6A0" ; "#118AB2" ; "#FFD166" ; "#073B4C" ; "#8D99AE" ) ;
    $$Theme = "ContrastCard" ;
      List ( "#4D3A70" ; "#596B8C" ; "#1F4D79" ; "#EB5757" ; "#27AE60" ; "#B0BEC5" ) ;
    $$Theme = "Dokondo" ;
      List ( "#D51E26" ; "#0E3344" ; "#5FA4A1" ; "#41C5E0" ; "#D8743D" ; "#D5432E" ) ;
    List ( "#4D3A70" ; "#596B8C" ; "#1F4D79" ; "#EB5757" ; "#27AE60" ; "#B0BEC5" )
  )
]
~~~

### 4.3 KPI nth-child Mapping Must Be Generated

After choosing the palette, generate a CSS string:

~~~filemaker
Set Variable [ $$KPI Card Colours ;
  Value:
    ".kpi-card:nth-child(1) { background: " & GetValue ( $KPI Card Colours ; 1 ) & "; }" & ¶ &
    ".kpi-card:nth-child(2) { background: " & GetValue ( $KPI Card Colours ; 2 ) & "; }" & ¶ &
    ".kpi-card:nth-child(3) { background: " & GetValue ( $KPI Card Colours ; 3 ) & "; }" & ¶ &
    ".kpi-card:nth-child(4) { background: " & GetValue ( $KPI Card Colours ; 4 ) & "; }" & ¶ &
    ".kpi-card:nth-child(5) { background: " & GetValue ( $KPI Card Colours ; 5 ) & "; }" & ¶ &
    ".kpi-card:nth-child(6) { background: " & GetValue ( $KPI Card Colours ; 6 ) & "; }"
]
~~~

This `$$KPI Card Colours` string must be used inside the final CSS.

---

## 5) CSS Generation Pattern

### 5.1 Use the Shared Dashboard CSS Script

The dashboard must call the shared style generator:

~~~filemaker
Perform Script [ Specified: From list ; “🖌️ Use Dashboard CSS” ; Parameter: "" ]
Set Variable [ $Styles ; Value: Get ( ScriptResult ) ]
Set Variable [ $Styles ; Value: "<style> " & $Styles & " </style>" ]
~~~

### 5.2 Inject Dynamic Theme CSS into Shared CSS

The shared CSS script must support injection points or you must append dynamic CSS after it.

Minimum dynamic CSS to append:
- `$$KPI Card Colours`
- chart container sizing overrides (if needed)
- progress circle stroke color
- grid/axis colors may be purely JS-driven

If the shared CSS does not support injection, the AI must do:

~~~filemaker
Set Variable [ $Styles ;
  Value: "<style> " & Get ( ScriptResult ) & ¶ & $$KPI Card Colours & " </style>"
]
~~~

---

## 6) HTML Block System

### 6.1 Dashboard HTML Is Built as Multiple Blocks

Each dashboard component is generated as its own variable:

- `$Cards HTML`
- `$Pie Chart HTML`
- `$Line Graph HTML`
- `$Bar Graph HTML`
- `$DataTable HTML`
- `$Timeline HTML`
- etc.

Then all are concatenated into one `$HTML`:

~~~filemaker
Set Variable [ $HTML ;
  Value:
    $Cards HTML & ¶ &
    $Pie Chart HTML & ¶ &
    $Pie Chart 2 HTML & ¶ &
    $Doughnut Chart HTML & ¶ &
    $Line Graph HTML & ¶ &
    $Bar Graph HTML & ¶ &
    $Timeline HTML
]
~~~

### 6.2 Positioning Strategy

The sample uses **absolute positioning with percentage layout**:

- top: `1.5%`, `22.5%`, `69%`, etc.
- left: `0.5%`, `21%`, `62%`, etc.
- width: `20%`, `30.2%`, `37.2%`, `49%`, etc.

The AI must preserve this style for consistency unless instructed to switch to CSS Grid/Flex.

### 6.3 KPI Cards Block Requirements

- KPI cards are links (`<a href='#...'>`)
- They carry class `kpi-card`
- They contain icon (often SVG) + value + label
- They rely on `$$KPI Card Colours` nth-child mapping

Minimum required structure:

~~~html
<div class='cards' style='position:absolute; top:1.5%; left:0.5%; gap:0.5%; width:99%; height:20%;'>
  <a href='#kpi-1' class='kpi-card'>
    <div class='kpi-title'>Total Products</div>
    <div class='kpi-value' id='kpiTotalProducts'>1,245</div>
  </a>
</div>
~~~

### 6.4 Chart Card Block Requirements

Every chart must be inside a `.chart-card` container and include:

- `<h2>Title</h2>`
- `.chart-container`
- `<canvas id='...'></canvas>`

Example:

~~~html
<div class="chart-card" style="position:absolute; top:22.5%; left:0.5%; width:20%; height:45%">
  <h2>Customer Satisfaction</h2>
  <div class="chart-container" style="width:100%; height:70%;">
    <canvas id="pieChart"></canvas>
  </div>
</div>
~~~

### 6.5 Non-Chart Visuals (Progress, Counter, Timeline)

These are still treated as HTML blocks and must have matching JS:

- Progress Circle: `<canvas id='progressCircle'>`
- Counter: `<div class='counter' id='counter'>0</div>`
- Progress Bar: `<div class='progress-bar' id='progressBar'>`
- Timeline Fill: `<div id='timelineFill'>` (or similar)

---

## 7) JavaScript Block System

### 7.1 Dashboard JS Is Built as Multiple Blocks

Each component’s JS is built into its own variable:

- `$Pie Chart JS`
- `$Line Graph JS`
- `$Progress Circle JS`
- `$Counter JS`
- etc.

Then concatenated into `$Scripts`:

~~~filemaker
Set Variable [ $Scripts ;
  Value:
    "<script>" & ¶ &
    $Pie Chart JS & ¶ &
    $Line Graph JS & ¶ &
    $Progress Circle JS & ¶ &
    $Counter JS & ¶ &
    "</script>"
]
~~~

### 7.2 ChartJS Must Be Available Before Any Chart Code Runs

The final page must load ChartJS before `$Scripts`.

Your pattern options:

1. Inline `<script>` injection from `$Dashboard JS` in `<head>`
2. External CDN `<script src='...'>` in `<head>` (if allowed)
3. A stored JS blob in FileMaker (as shown)

The sample uses:

~~~filemaker
"<script>" & $Dashboard JS & "</script>"
~~~

This implies `$Dashboard JS` contains ChartJS library code or loader code.

### 7.3 Theme-Driven Colors in JS

The AI must use the theme variables in JS strings, especially:

- pie colors (`$PieColours`)
- border widths (`$PieBorderWidth`)
- line dataset colors (`$Line Graph Colours`)
- axis colors (`$AxisColours _X`)
- grid colors (`$GridColours`)
- bar colors (`$Bar Chart Colours`)
- stacked colors (`$Stacked Bars Colours`)
- gauge colors (`$Gauge Colours`)

Example snippet shape (string-building idea):

~~~js
options: {
  scales: {
    x: { ticks: { color: 'AXIS_X_COLOR' }, grid: { color: 'GRID_COLOR' } },
    y: { ticks: { color: 'AXIS_X_COLOR' }, grid: { color: 'GRID_COLOR' } }
  }
}
~~~

Then replace placeholders in FileMaker, or concatenate values directly into the JS string.

### 7.4 Defensive JS: Wait for DOM Ready (Optional but Recommended)

If WebDirect timing issues occur, wrap chart creation inside:

~~~js
(function () {
  const run = () => { /* create charts */ };
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", run);
  } else {
    run();
  }
})();
~~~

The sample uses immediate execution. The AI may use the DOM-ready pattern if dashboards fail to render in some contexts.

---

## 8) Final Page Assembly Pattern

### 8.1 `$$Page` Must Be Full HTML Document

The final page must include:

- `<!DOCTYPE html>`
- `<html lang="en">`
- `<head>`
  - charset
  - viewport
  - title
  - ChartJS preload script
  - `$Styles`
- `</head>`
- `<body>`
  - `$HTML`
  - `$Scripts` (or scripts appended after HTML)
- `</body>`
- `</html>`

### 8.2 Example Assembly (Pattern)

~~~filemaker
Set Variable [ $$Page ;
  Value:
    "<!DOCTYPE html>" & 
    "<html lang='en'>" &
    "<head>" &
      "<meta charset='UTF-8'>" &
      "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" &
      "<title>Dashboard</title>" &
      "<script>" & $Dashboard JS & "</script>" &
      $Styles &
    "</head>" &
    "<body>" &
      $HTML &
      $Scripts &
    "</body>" &
    "</html>"
]
~~~

### 8.3 WebDirect Stabilization

After setting `$$Page`, the script should:

~~~filemaker
Perform Script [ Specified: From list ; “WebDirect Pause” ; Parameter: "" ]
Refresh Window [ Flush cached join results ; Flush cached external data ]
~~~

---

## 9) Full Script Blueprint (AI Output Template)

> The AI Agent should generate a dashboard script using this skeleton, filling in the theme maps, HTML blocks, and JS blocks.

~~~filemaker
Set Variable [ $$App Section ; Value: "Dashboard" ]

/* External JS preload */
Set Variable [ $Dashboard JS ;
  Value: Let (
    [
      sql = "Select JS From ChartJS" ;
      fieldseparator = "xxxxxxxxxx" ;
      rowseparator = "yyyyyyyyyy" ;
      result = ExecuteSQL ( sql ; fieldseparator ; rowseparator )
    ] ;
    result
  )
]

/* Theme variables */
Set Variable [ $KPI Card Colours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $PieBorderWidth ; Value: If ( /* theme conditions */ ; 2 ; 1 ) ]
Set Variable [ $PieColours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $Line Graph Colours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $AxisColours _X ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $GridColours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $Bar Chart Colours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $Stacked Bars Colours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $Gauge Colours ; Value: Case ( /* theme mapping */ ) ]
Set Variable [ $Progress Circle Stroke ; Value: Case ( /* theme mapping */ ) ]

/* KPI dynamic CSS */
Set Variable [ $$KPI Card Colours ;
  Value:
    ".kpi-card:nth-child(1) { background: " & GetValue ( $KPI Card Colours ; 1 ) & "; }" & ¶ &
    ".kpi-card:nth-child(2) { background: " & GetValue ( $KPI Card Colours ; 2 ) & "; }" & ¶ &
    ".kpi-card:nth-child(3) { background: " & GetValue ( $KPI Card Colours ; 3 ) & "; }" & ¶ &
    ".kpi-card:nth-child(4) { background: " & GetValue ( $KPI Card Colours ; 4 ) & "; }" & ¶ &
    ".kpi-card:nth-child(5) { background: " & GetValue ( $KPI Card Colours ; 5 ) & "; }" & ¶ &
    ".kpi-card:nth-child(6) { background: " & GetValue ( $KPI Card Colours ; 6 ) & "; }"
]

/* Overall CSS */
Perform Script [ Specified: From list ; “🖌️ Use Dashboard CSS” ; Parameter: "" ]
Set Variable [ $Styles ; Value: Get ( ScriptResult ) ]
Set Variable [ $Styles ; Value: "<style>" & $Styles & ¶ & $$KPI Card Colours & "</style>" ]

/* HTML blocks */
Set Variable [ $Cards HTML ; Value: "..." ]
Set Variable [ $Pie Chart HTML ; Value: "..." ]
Set Variable [ $Line Graph HTML ; Value: "..." ]
Set Variable [ $DataTable HTML ; Value: "..." ]
Set Variable [ $Timeline HTML ; Value: "..." ]

Set Variable [ $HTML ;
  Value: $Cards HTML & ¶ & $Pie Chart HTML & ¶ & $Line Graph HTML & ¶ & $DataTable HTML & ¶ & $Timeline HTML
]

/* JS blocks */
Set Variable [ $Pie Chart JS ; Value: "..." ]
Set Variable [ $Line Graph JS ; Value: "..." ]
Set Variable [ $Progress Circle JS ; Value: "..." ]
Set Variable [ $Counter JS ; Value: "..." ]
Set Variable [ $Timeline JS ; Value: "..." ]

Set Variable [ $Scripts ;
  Value: "<script>" & ¶ &
    $Pie Chart JS & ¶ &
    $Line Graph JS & ¶ &
    $Progress Circle JS & ¶ &
    $Counter JS & ¶ &
    $Timeline JS & ¶ &
  "</script>"
]

/* Full page */
Set Variable [ $$Page ;
  Value:
    "<!DOCTYPE html>" &
    "<html lang='en'>" &
    "<head>" &
      "<meta charset='UTF-8'>" &
      "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" &
      "<title>Dashboard</title>" &
      "<script>" & $Dashboard JS & "</script>" &
      $Styles &
    "</head>" &
    "<body>" &
      $HTML &
      $Scripts &
    "</body>" &
    "</html>"
]

Perform Script [ Specified: From list ; “WebDirect Pause” ; Parameter: "" ]
Refresh Window [ Flush cached join results ; Flush cached external data ]
~~~

---

## 10) Component Recipes (AI Must Be Able to Generate)

This section teaches the AI how to generate each dashboard component in a repeatable way.

### 10.1 KPI Cards Recipe

**HTML requirements**
- `div.cards`
- children: `a.kpi-card`
- each card contains:
  - icon (svg optional)
  - `.kpi-title`
  - `.kpi-value` with `id`

**JS requirements**
- optional: animate numbers or update from data

**Example HTML (string form shape)**
~~~html
<div class='cards' style='position:absolute; top:1.5%; left:0.5%; gap:0.5%; width:99%; height:20%;'>
  <a href='#total-products' class='kpi-card'>
    <div class='kpi-title'>Total Products</div>
    <div class='kpi-value' id='kpiTotalProducts'>1245</div>
  </a>
  <a href='#total-customers' class='kpi-card'>
    <div class='kpi-title'>Total Customers</div>
    <div class='kpi-value' id='kpiTotalCustomers'>320</div>
  </a>
</div>
~~~

### 10.2 Pie Chart Recipe

**HTML**
- `canvas id="pieChart"`

**JS**
- new Chart(ctx, { type: 'pie', data: {...}, options: {...} })

Theme dependencies:
- `$PieColours`
- `$PieBorderWidth`

### 10.3 Doughnut Chart Recipe

Same as pie, type = `doughnut`.

### 10.4 Line Graph Recipe

Theme dependencies:
- `$Line Graph Colours` (dataset style chunks)
- `$AxisColours _X`
- `$GridColours`

The AI must generate dataset color blocks as raw JS fragments, example style:

~~~js
datasets: [
  { label: 'Sales', data: [..], borderColor: '...', backgroundColor: 'rgba(...)' },
  { label: 'Orders', data: [..], borderColor: '...', backgroundColor: 'rgba(...)' }
]
~~~

### 10.5 Bar Chart Recipe

Theme dependencies:
- `$Bar Chart Colours` (backgroundColor + borderColor arrays)

### 10.6 Horizontal Bar Chart Recipe

ChartJS modern versions use:
- type: 'bar'
- options: `indexAxis: 'y'`

### 10.7 Stacked Bar Chart Recipe

Use:
- `scales: { x: { stacked: true }, y: { stacked: true } }`

Theme dependencies:
- `$Stacked Bars Colours` (dataset style chunks)

### 10.8 Gauge Recipe

If implemented using ChartJS doughnut with partial ring:
- type: 'doughnut'
- rotation and circumference control
- theme gauge colors from `$Gauge Colours`

### 10.9 Progress Circle Recipe

HTML:
- `<canvas id='progressCircle' width='150' height='150'></canvas>`
- `<div id='progress_circleValue'></div>` (if used)

JS:
- draw arc based on percentage
- use `$Progress Circle Stroke`

### 10.10 Counter Recipe

HTML:
- `<div class='counter' id='counter'>0</div>`

JS:
- animate number from 0 to target over duration
- use requestAnimationFrame (or interval)

### 10.11 Progress Bar Recipe

HTML:
- `<div class='progress-bar' id='progressBar'></div>`

JS:
- animate width until target percentage

### 10.12 Data Table Recipe

HTML:
- `<table>` with `<thead>` and `<tbody>`
- table must be readable within `.chart-card`

Optional JS:
- none, can be static

### 10.13 Gantt Chart Recipe (HTML Table)

HTML:
- table rows with bars created via CSS classes

Optional JS:
- none, can be static

### 10.14 Timeline Recipe

HTML:
- progress line + fill element with `id='timelineFill'`

JS:
- set width based on progress percentage

---

## 11) Quality Rules for AI Output

### 11.1 Single Responsibility Per Variable

- One variable per block (HTML or JS).
- Do not create one mega variable for everything unless assembling.

### 11.2 Use Predictable IDs

Use semantic IDs:
- `pieChart`
- `pieChart2`
- `doughnutChart`
- `lineChart`
- `lineChartAlt`
- `barChart`
- `barChartAlt`
- `horizontalBarChart`
- `horizontalBarChartAlt`
- `stackedBarChart`
- `gaugeChart`
- `progressCircle`
- `counter`
- `progressBar`
- `timelineFill`

### 11.3 Keep Inline Styles Minimal and Consistent

If using inline absolute positioning, do it consistently:
- top/left/width/height in percentages
- keep `max-width` consistent with `width`

### 11.4 Fail Gracefully

If ChartJS is missing:
- dashboard should still load
- non-chart blocks should still display
- optional: show a message in chart containers

### 11.5 Avoid Colliding Globals

Prefer:
- self-invoking wrappers
- local const variables

---

## 12) Ambiguities and Clarifications Needed (You Must Answer)

The sample code implies several rules, but they are not fully defined. Please clarify these so the AI training can be exact.

### 12.1 What Exactly Is in `ChartJS::JS`?

- Is it the full ChartJS library minified code?
- Or is it a loader that loads ChartJS from CDN?
- Or is it your own wrapper functions?

The AI needs to know whether to:
- embed the library, or
- reference it externally, or
- assume it exists already.

### 12.2 ExecuteSQL Returns Multiple Rows

Your SQL is:

- `Select JS From ChartJS`

If ChartJS table contains multiple records:
- Which record should be used?
- Do you want:
  - the first row only
  - a specific row by `Name` or `Version`
  - concatenation of all rows

If there is a field like `ChartJS::Name` or `ChartJS::Key`, the AI should filter.

### 12.3 Where Does `$$Page` Get Rendered?

After setting `$$Page`, what script or WebViewer object consumes it?

- Is there a standard object name (example: `"wvMain"`)?
- Is there a standard script step: `Set Web Viewer [ Object Name: ... ; Action: "Set HTML" ; HTML: $$Page ]`?

The sample code stops at `$$Page` + `WebDirect Pause` + `Refresh Window`, but does not show the WebViewer injection step.

### 12.4 What Does “🖌️ Use Dashboard CSS” Return?

- Does it return only base CSS, and you append dynamic parts?
- Or does it accept parameters (theme, dynamic CSS, etc.)?

In the sample, the parameter is empty. If it supports parameters, the AI should use them.

### 12.5 Theme Canon: What Are the Official Theme Names?

The sample references many themes (some truncated). Please confirm the official list used in CauferoAppStarter, for example:

- AquaView
- Aurora
- ContrastCard
- Dokondo
- Electric Eclipse
- Ethereal Workspace
- Frosted Horizons
- Lumen Clean UI
- Minimal Elegance
- Modern Flex UI
- Modern Minimalist
- KoolTool
- NeatFrame
- (others)

The AI must match theme names exactly.

### 12.6 Chart Colors Format Is Mixed (List vs JS String)

Some theme variables are:
- FileMaker `List()` values
Some are:
- JS literal arrays inside strings like: `"'#00796B', '#80CBC4', ...'"`

Please confirm the standard:
- Should `$PieColours` be a JS array literal string only?
- Or should it be a FileMaker list that the AI converts to JS?

### 12.7 The ¶ Character Usage

Your code uses the `¶` symbol as a line delimiter inside strings.

- Is the AI required to use `¶` always for JS/CSS strings?
- Or is `& ¶ &` the standard only for FileMaker readability?

If you want strict consistency, define it.

---

## 13) AI Completion Checklist (Must Pass Before Output Is Accepted)

Before the AI finalizes any dashboard generation script, it must verify:

1. `$$App Section` set to `"Dashboard"`
2. `$Dashboard JS` retrieval defined and used in `<head>`
3. Theme variables computed from `$$Theme`
4. `$$KPI Card Colours` CSS mapping generated
5. `🖌️ Use Dashboard CSS` called and included in `$Styles`
6. Every `<canvas id='X'>` has matching JS `getElementById('X')`
7. `$HTML` contains all component blocks
8. `$Scripts` concatenates all JS blocks inside `<script>...</script>`
9. `$$Page` includes: doctype, html, head, body
10. WebDirect stabilization is executed (pause + refresh)
11. No missing variable references
12. No mismatched quotes or broken HTML tags

---

## 14) Minimal Working Example (Compressed Concept)

> This is not the full sample, but a small canonical example the AI can always generate as a starting dashboard: 2 KPI cards + 1 pie chart.

~~~filemaker
Set Variable [ $$App Section ; Value: "Dashboard" ]

Set Variable [ $Dashboard JS ;
  Value: Let (
    [
      sql = "Select JS From ChartJS" ;
      fieldseparator = "xxxxxxxxxx" ;
      rowseparator = "yyyyyyyyyy" ;
      result = ExecuteSQL ( sql ; fieldseparator ; rowseparator )
    ] ;
    result
  )
]

Set Variable [ $KPI Card Colours ;
  Value: Case (
    $$Theme = "Dokondo" ; List ( "#D51E26" ; "#0E3344" ; "#5FA4A1" ; "#41C5E0" ; "#D8743D" ; "#D5432E" ) ;
    List ( "#4D3A70" ; "#596B8C" ; "#1F4D79" ; "#EB5757" ; "#27AE60" ; "#B0BEC5" )
  )
]

Set Variable [ $$KPI Card Colours ;
  Value:
    ".kpi-card:nth-child(1) { background: " & GetValue ( $KPI Card Colours ; 1 ) & "; }" & ¶ &
    ".kpi-card:nth-child(2) { background: " & GetValue ( $KPI Card Colours ; 2 ) & "; }"
]

Perform Script [ Specified: From list ; “🖌️ Use Dashboard CSS” ; Parameter: "" ]
Set Variable [ $Styles ; Value: Get ( ScriptResult ) ]
Set Variable [ $Styles ; Value: "<style>" & $Styles & ¶ & $$KPI Card Colours & "</style>" ]

Set Variable [ $Cards HTML ;
  Value:
    "<div class='cards' style='position:absolute; top:1.5%; left:0.5%; gap:0.5%; width:99%; height:20%;'>" &
      "<a href='#kpi-1' class='kpi-card'>" &
        "<div class='kpi-title'>Total Products</div>" &
        "<div class='kpi-value' id='kpiTotalProducts'>1245</div>" &
      "</a>" &
      "<a href='#kpi-2' class='kpi-card'>" &
        "<div class='kpi-title'>Total Customers</div>" &
        "<div class='kpi-value' id='kpiTotalCustomers'>320</div>" &
      "</a>" &
    "</div>"
]

Set Variable [ $Pie Chart HTML ;
  Value:
    "<div class='chart-card' style='position:absolute; top:22.5%; left:0.5%; width:30%; height:45%'>" &
      "<h2>Customer Satisfaction</h2>" &
      "<div class='chart-container' style='width:100%; height:80%;'>" &
        "<canvas id='pieChart'></canvas>" &
      "</div>" &
    "</div>"
]

Set Variable [ $HTML ; Value: $Cards HTML & ¶ & $Pie Chart HTML ]

Set Variable [ $Pie Chart JS ;
  Value:
    "(function () {" &
      "const el = document.getElementById('pieChart');" &
      "if (!el || typeof Chart === 'undefined') return;" &
      "const ctx = el.getContext('2d');" &
      "new Chart(ctx, {" &
        "type: 'pie'," &
        "data: {" &
          "labels: ['Very Satisfied','Satisfied','Neutral','Unsatisfied','Very Unsatisfied']," &
          "datasets: [{" &
            "data: [45,25,15,10,5]," &
            "backgroundColor: ['#D51E26','#0E3344','#5FA4A1','#41C5E0','#D8743D']," &
            "borderWidth: 1" &
          "}]" &
        "}," &
        "options: { responsive: true, maintainAspectRatio: false }" &
      "});" &
    "})();"
]

Set Variable [ $Scripts ; Value: "<script>" & ¶ & $Pie Chart JS & ¶ & "</script>" ]

Set Variable [ $$Page ;
  Value:
    "<!DOCTYPE html><html lang='en'><head>" &
      "<meta charset='UTF-8'>" &
      "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" &
      "<title>Dashboard</title>" &
      "<script>" & $Dashboard JS & "</script>" &
      $Styles &
    "</head><body>" &
      $HTML &
      $Scripts &
    "</body></html>"
]

Perform Script [ Specified: From list ; “WebDirect Pause” ; Parameter: "" ]
Refresh Window [ Flush cached join results ; Flush cached external data ]