# CauferoAppStarter Documentation
## Building a List Page for Any Entity Type (AI Agent Training Spec)

### Purpose
This document trains an AI Agent to create a fully working **List Page generator script** for any **Entity Type** inside the FileMaker file **CauferoAppStarter**.

A "List Page" in this system is generated by:
1) Setting a standard set of script variables (SQL, headers, column behavior, UI labels, empty-state content).
2) Calling a shared renderer script (`+++ Display List HTML` or legacy `+++ Display List HTML_`) with a strict parameter order.
3) Setting any post-render UI state globals (example: `$$Tab To Show`).

This document is written as a build spec. Follow it exactly.

---

# 1. Definitions

## 1.1 Entity Type
An Entity Type is a table-backed concept that has:
- A FileMaker table (example: `Departments`, `Staff`, `Job Titles`)
- A "List Page generator script" (example: `+++ Staff List Page`)
- A "Details Page script" (example: `+++ Staff Details Page`)
- Optional "Add New Record script" (example: `Add New Staff`)

## 1.2 List Page Generator Script
A List Page generator script:
- Sets `$$App Section`
- Defines SQL (first selected column must be the record ID)
- Defines column headers and optional layout rules
- Defines search behavior
- Defines empty-state visuals and messages
- Calls the shared list renderer script with a strict parameter order

---

# 2. FileMaker Script Naming Rules

Use these conventions consistently:
- List Page script name: `+++ <Entity Name> List Page`
- Details Page script name: `+++ <Entity Name> Details Page`
- Add New script name: `Add New <Entity Name>`

Examples:
- `+++ Department List Page`
- `+++ Job Title Details Page`
- `Add New Staff`

---

# 3. Shared Renderer Scripts (Critical)

There are two renderer scripts seen in the samples:

- `+++ Display List HTML`
- `+++ Display List HTML_`

They use different parameter signatures.

## 3.1 Preferred Renderer (New Signature)
Use:
- `+++ Display List HTML`

It supports column widths and categorization (grouping).

## 3.2 Legacy Renderer (Old Signature)
Use:
- `+++ Display List HTML_`

It appears to be an older signature that does not accept column widths and categorization.

You must choose the renderer that matches the parameter list you are passing.

---

# 4. Data Contract: SQL Output Requirements (Critical)

The SQL query must follow these rules:

## 4.1 First Selected Column Must Be Record ID
The very first selected field must be the primary key (ID) of the entity record you want to view.

Examples:
- `SELECT t1.ID, t1.Name, ... FROM Departments t1 ...`
- `SELECT t1.ID, t1."Staff Number", ... FROM Staff t1 ...`

The renderer depends on the first column being ID so it can route row actions to the correct record.

## 4.2 Output Columns After ID Must Match List UI Columns (With 2 Important Exceptions)
The SQL returns a dataset. The UI will show:
- A computed `S/N` column
- The columns you provide headers for (data columns)
- An `Actions` column on the far right (row actions)

So your `Column Headers` must describe the data columns that appear in the list, plus `S/N` and `Actions`.

### Exception A: Status must be the last data column (when used)
If the SQL query returns a status value AND the list page will display a status column, then:
- Status must be the **last data column** in the list (right before `Actions`)
- Therefore, status must appear as the **last data header** in `$Column Headers` before `Actions`

Example (good):
- `"S/N,Name,Role,Status,Actions"`

Example (bad):
- `"S/N,Status,Name,Role,Actions"`

### Exception B: Categorization field must be returned by SQL but hidden from displayed data columns
If the list will be categorized/grouped, the categorization value **must be present in the SQL recordset**, but it **must NOT be displayed as a visible data column**.

That means:
- You include the category field in the SQL `SELECT` list
- But you do **not** include the category label in `$Column Headers`

This is how the renderer can group rows by the category value without showing it as a column.

**Key concept:**
- SQL can return more columns than the UI displays.
- The categorization column index points to the position of the category field in the SQL resultset (see indexing rules below).

Example:
SQL selected fields:
- `ID, Name, Role, Category`

Displayed headers:
- `"S/N,Name,Role,Actions"`

Categorization column:
- The category is the **4th selected field in the SQL recordset** (after ID is 1st, Name is 2nd, Role is 3rd, Category is 4th)
- So `$Categorization Column = 4`

Result:
- Category does not show as a visible column
- But the list groups by category

## 4.3 Aggregations Require GROUP BY
If SQL uses `COUNT(...)` or any aggregation, add a correct `GROUP BY` to match non-aggregated fields.

Example pattern:
- `COUNT(t4."Staff ID") AS NumberOfStaff`
- `GROUP BY t1.ID, t1.Name, t2."First Name", t2."Last Name"`

## 4.4 Consistent Aliasing
Use table aliases in the form:
- `t1`, `t2`, `t3`, `t4`

This keeps SQL consistent and predictable.

## 4.5 Friendly Display Fields
Use computed fields for readable UI text:
- Full name: `t1."First Name" || ' ' || t1."Last Name" AS FullName`
- Status mapping: `CASE WHEN ... THEN ... ELSE ... END AS Status`

---

# 5. List Page Variable Set (Master Spec)

This section defines the variables your List Page script must set.

There are two variants:
- New variant for `+++ Display List HTML` (recommended)
- Legacy variant for `+++ Display List HTML_`

---

## 5.1 Variables for New Renderer: `+++ Display List HTML` (Recommended)

### Required
- `$$App Section`
- `$SQL`
- `$SQL Condition`
- `$Column Headers`
- `$Status Column`
- `$Date Columns`
- `$Number Columns`
- `$Categorization Column`
- `$Searchable Columns`
- `$Add New Record Script Name`
- `$View Record Script Name`
- `$Search Field Placeholder`
- `$Total Records Label`
- `$Add New Record Button Label`
- Empty-state icon (either SVG path or URL depending on your renderer implementation)
- Empty-state title
- Empty-state body

### Optional
- `$Column Widths` (highly recommended for stable UI sizing)

---

## 5.2 Variables for Legacy Renderer: `+++ Display List HTML_` (Old)

### Required
- `$$App Section`
- `$SQL`
- `$SQL Condition`
- `$Column Headers`
- `$Status Column`
- `$Date Columns`
- `$Number Columns`
- `$Searchable Columns`
- `$Add New Record Script Name`
- `$View Record Script Name`
- `$Search Field Placeholder`
- `$Total Records Label`
- `$Add New Record Button Label`
- Empty-state icon SVG path
- Empty-state title
- Empty-state body

This legacy signature does not include:
- `$Column Widths`
- `$Categorization Column`

---

# 6. Parameter Order (Strict)

The renderer script reads a single parameter string separated by `¶`. Order matters.

## 6.1 Parameter Order for `+++ Display List HTML` (New)

Pass parameters in this exact order:

1. `$SQL`
2. `$SQL Condition`
3. `$Column Headers`
4. `$Column Widths`
5. `$Status Column`
6. `$Date Columns`
7. `$Number Columns`
8. `$Categorization Column`
9. `$Searchable Columns`
10. `$Add New Record Script Name`
11. `$View Record Script Name`
12. `$Search Field Placeholder`
13. `$Total Records Label`
14. `$Add New Record Button Label`
15. `$No Record Found Icon` (SVG path or URL, depends on your implementation)
16. `$No Record Found Message Title`
17. `$No Record Found Message Body`

### Canonical call shape
~~~filemaker
Perform Script [
  Specified: From list ;
  “+++ Display List HTML” ;
  Parameter:
    $SQL & ¶ &
    $SQL Condition & ¶ &
    $Column Headers & ¶ &
    $Column Widths & ¶ &
    $Status Column & ¶ &
    $Date Columns & ¶ &
    $Number Columns & ¶ &
    $Categorization Column & ¶ &
    $Searchable Columns & ¶ &
    $Add New Record Script Name & ¶ &
    $View Record Script Name & ¶ &
    $Search Field Placeholder & ¶ &
    $Total Records Label & ¶ &
    $Add New Record Button Label & ¶ &
    $No Record Found Icon & ¶ &
    $No Record Found Message Title & ¶ &
    $No Record Found Message Body
]
~~~

## 6.2 Parameter Order for `+++ Display List HTML_` (Legacy)

Pass parameters in this exact order:

1. `$SQL`
2. `$SQL Condition`
3. `$Column Headers`
4. `$Status Column`
5. `$Date Columns`
6. `$Number Columns`
7. `$Searchable Columns`
8. `$Add New Record Script Name`
9. `$View Record Script Name`
10. `$Search Field Placeholder`
11. `$Total Records Label`
12. `$Add New Record Button Label`
13. `$No Record Found Icon SVG Path`
14. `$No Record Found Message Title`
15. `$No Record Found Message Body`

### Canonical call shape
~~~filemaker
Perform Script [
  Specified: From list ;
  “+++ Display List HTML_” ;
  Parameter:
    $SQL & ¶ &
    $SQL Condition & ¶ &
    $Column Headers & ¶ &
    $Status Column & ¶ &
    $Date Columns & ¶ &
    $Number Columns & ¶ &
    $Searchable Columns & ¶ &
    $Add New Record Script Name & ¶ &
    $View Record Script Name & ¶ &
    $Search Field Placeholder & ¶ &
    $Total Records Label & ¶ &
    $Add New Record Button Label & ¶ &
    $No Record Found Icon SVG Path & ¶ &
    $No Record Found Message Title & ¶ &
    $No Record Found Message Body
]
~~~

---

# 7. Variable Semantics and Allowed Formats

This section defines exact meaning and format rules.

## 7.1 `$$App Section`
String. The human-friendly title of the current section.

Examples:
- `"Staff List"`
- `"Job Titles List"`
- `"Department List"`

## 7.2 `$SQL`
String. SQL SELECT statement.

Rules:
- Must start with `SELECT`
- Must select `ID` first
- Must produce the dataset needed by the list
- If list is categorized, SQL must include the category field in the selected fields even if it is not displayed

Example pattern:
~~~sql
SELECT
  t1.ID,
  t1.Name,
  COUNT(t3.ID) AS TotalChildRecords
FROM SomeTable t1
LEFT JOIN ChildTable t3 ON t1.ID = t3."Parent ID"
GROUP BY t1.ID, t1.Name
~~~

## 7.3 `$SQL Condition`
This variable is used as a condition value to influence list output.

Observed usages:
- Simple list: `1`
- Conditional list by layout: `Case ( $$Layout Name = ... ; ... ; )`

Format rules:
- Can be a number or text
- Must be a single scalar value (no line breaks)

Important:
- The way this condition is applied inside the renderer is not shown in samples. Treat it as a required pipe variable that the renderer expects, even if it is `1`.

## 7.4 `$Column Headers`
Comma-separated list of column header labels.

Rules:
- Must include `S/N` as the first label
- Must include `Actions` as the last label
- Labels must match the displayed columns
- If categorization is enabled, the category field must NOT appear in headers (it is hidden but returned by SQL)
- If status is displayed, `Status` must be the last data header before `Actions`
- The generator must avoid overly cramped tables (see Section 8.1)

Examples:
- `"S/N,Staff #,Full Name,Gender,Job Title,Department,Status,Actions"`
- `"S/N,Job Title,Department,Total Staff,Actions"`

Categorization example (category returned in SQL but hidden in headers):
- SQL selects: `ID, Name, Role, Category`
- Headers: `"S/N,Name,Role,Actions"`

## 7.5 `$Column Widths` (New Renderer)
Comma-separated numeric percentages or proportional widths.

Rules:
- Count must match the number of headers
- Include widths for `S/N` and `Actions`
- Use widths to prevent cramped columns on a 13-inch screen with a side menu

Examples:
- `"5,10,20,10,20,20,10,5"`
- `"5,50,20,20,5"`

If not used, pass an empty string `""` only if the renderer allows it.

## 7.6 `$Status Column`
Index of the status column in the displayed list, using 1-based indexing aligned to `Column Headers`.

Rules:
- Only set this if status is displayed
- If set, status must be the last data column before `Actions`

Examples:
- `"S/N,Name,Role,Status,Actions"` => `$Status Column = 4`
- If no status column exists: `""` (empty string)

## 7.7 `$Date Columns`
Comma-separated indexes (1-based) of columns that should be formatted as dates.

Examples:
- InPatients list: `"2"`
- No date columns: `""`

## 7.8 `$Number Columns`
Comma-separated indexes (1-based) of columns that should be formatted as numbers.

Examples:
- `""` if none
- `"4,7"` if columns 4 and 7 are numeric

## 7.9 `$Categorization Column` (New Renderer)
A single index (1-based) or empty string.

Purpose:
- Used to group or categorize rows by a column value (example: group by date, group by industry).

Critical rule (hidden category field):
- If categorization is enabled, the category value must be present in the SQL selected fields
- The category value should not be included in `$Column Headers` (hidden from the UI)
- `$Categorization Column` should point to the category field position in the SQL resultset (see Open Questions for exact index-space confirmation)

Examples:
- SQL selects: `ID, AdmissionDate, PatientName, Ward`
  - Group by AdmissionDate => `$Categorization Column = 2`
- SQL selects: `ID, Name, Role, Industry`
  - Headers: `"S/N,Name,Role,Actions"`
  - Group by Industry => `$Categorization Column = 4`

No grouping:
- `$Categorization Column = ""`

## 7.10 `$Searchable Columns`
Comma-separated indexes (1-based) that are included in search filtering.

Examples:
- `"1,2,3"`
- `"1,2,3,4,5,6"`

Note:
- Index meanings must match the renderer's internal mapping. In samples, it appears to refer to displayed columns excluding `Actions`. Confirm in Open Questions section.

## 7.11 `$Add New Record Script Name`
Text. Script name to run when user clicks the "Add New" button.

Examples:
- `"Add New Staff"`
- `""` if no add button is needed

## 7.12 `$View Record Script Name`
Text. Script name to run when user clicks a row or a "View" action.

Examples:
- `"+++ Staff Details Page"`
- Conditional: `Case ( $$Layout Name = ... ; "+++ X Details Page" ; ... )`

## 7.13 `$Search Field Placeholder`
Text. Placeholder inside search field.

Examples:
- `"Search staff list"`
- Conditional by layout: `Case ( $$Layout Name = ... ; "Search patients on admission" ; ... )`

## 7.14 `$Total Records Label`
Text. Label next to total record count.

Examples:
- `"Total Staff"`
- `"Business Types"`
- Conditional by layout: `"Discharged Patients"`

## 7.15 `$Add New Record Button Label`
Text. Label of add button.

Examples:
- `"Add New Staff Member"`
- `""` if no add button

## 7.16 Empty-state Content
Used when there are no records.

Supported types observed:
- SVG path string: `$No Record Found Icon SVG Path`
- External image URL: `$No Record Found Icon URL`

Messages observed:
- `$No Record Found Message Title`
- `$No Record Found Message Body`

Rules:
- Provide at least icon + title + body unless the UI intentionally hides them
- Keep title short
- Body should be one sentence

---

# 8. Build Procedure (AI Agent Workflow)

Follow this exact sequence to build a new entity list page script.

## Step 1: Identify the Entity and Its Dataset
Collect:
- Table name (example: `Departments`)
- Primary key field (assumed: `ID`)
- Core display fields (example: `Name`)
- Related joins needed for display (example: HOD Staff name, Department counts)

## Step 2: Decide the Visible Columns
Define the list columns in human terms:
- Example: Department Name, Head of Department, Total Staff

Then map each column to a SQL expression.

Rules to apply:
- If status will be displayed, place it as the last data column (right before Actions)
- If categorization will be used, decide the category field and include it in SQL, but do not display it as a column

## Step 3: Build the SQL
Rules recap:
- First select: `t1.ID`
- Use left joins where needed
- Use group by when using count
- Use aliases for readability
- If categorization is enabled: include the category field in `SELECT` (even though it will be hidden)
- If status is displayed: ensure the status expression is selected such that it becomes the last visible data column in the UI

## Step 4: Create Column Headers
Create a comma-separated string:
- First label: `S/N`
- Last label: `Actions`
- Middle labels match your visible data columns

Rules to apply:
- If status is displayed, `Status` must be the last header before `Actions`
- If categorization is enabled, do not include the category label in headers

## Step 5: Define Optional Column Widths (New Renderer)
Create widths string with same count as headers.

## Step 6: Define Column Behaviors
Set:
- `$Status Column` or empty
- `$Date Columns` or empty
- `$Number Columns` or empty
- `$Categorization Column` or empty
- `$Searchable Columns` indexes

Reminder:
- `$Status Column` index must point to the status header, and status must be the last data header before Actions
- `$Categorization Column` index must point to the category field in the SQL resultset even if that category is not displayed in headers

## Step 7: Define Scripts and Labels
Set:
- `$Add New Record Script Name`
- `$View Record Script Name`
- `$Search Field Placeholder`
- `$Total Records Label`
- `$Add New Record Button Label`

## Step 8: Define Empty-state
Set:
- icon (SVG path or URL)
- title
- body

## Step 9: Call Renderer Script
Choose one:
- New: `+++ Display List HTML`
- Legacy: `+++ Display List HTML_`

Pass parameters in the exact order.

## Step 10: Set Post-render UI State
At minimum:
- `Set Variable [ $$Tab To Show ; Value: 1 ]`

Some modules reset additional globals. Do so only when the module requires it.

---

# 8.1 Column Count and Layout Density Rule (Anti-Cramping Rule)

The displayed list must not feel cramped.

Context:
- The list page is mostly displayed with a **side menu**
- The typical viewing device is a **13-inch screen**

Rule:
- As a general target, the number of **displayed columns** (data columns) should be around **3 to 5**.
- The generator may choose **3, 4, 5**, and in rare cases **6** columns if the data still reads cleanly.
- The generator may choose fewer columns if the fields are long (example: long names, long descriptions).
- The generator must use discretion to prevent tight column widths and unreadable rows.

Important:
- This is a discretion rule, not a hard limit.
- Prioritize readability over "show everything."
- If there are many useful fields, choose the best few for the list and keep the rest for the Details Page.
- Use `$Column Widths` (new renderer) to help protect readability.

Practical heuristics (apply common sense):
- If 1 or more columns will contain long text, reduce the total number of displayed columns.
- Prefer short, high-signal columns in the list (example: Name, Code, Category label if displayed, Key count metric).
- Defer long or secondary fields to the Details Page.

---

# 9. Canonical Templates

## 9.1 New Renderer Template (Recommended)

~~~filemaker
# +++ <Entity Name> List Page

Set Variable [ $$App Section ; Value: "<Entity Name> List" ]

Set Variable [ $SQL ; Value:
"SELECT
  t1.ID,
  <field_expr_1>,
  <field_expr_2>,
  <optional_hidden_category_expr>,
  <optional_status_expr>
FROM <TableName> t1
<joins>
<optional_where_or_grouping>
"
]

Set Variable [ $SQL Condition ; Value: 1 ]

Set Variable [ $Column Headers ; Value: "S/N,<Header 1>,<Header 2>,<optional Status>,Actions" ]
Set Variable [ $Column Widths ; Value: "<w1>,<w2>,<w3>,<w4>,<w5>" ]

Set Variable [ $Status Column ; Value: "" ]
Set Variable [ $Date Columns ; Value: "" ]
Set Variable [ $Number Columns ; Value: "" ]
Set Variable [ $Categorization Column ; Value: "" ]

Set Variable [ $Searchable Columns ; Value: "1,2,3" ]

Set Variable [ $Add New Record Script Name ; Value: "Add New <Entity Name>" ]
Set Variable [ $View Record Script Name ; Value: "+++ <Entity Name> Details Page" ]

Set Variable [ $Search Field Placeholder ; Value: "Search <entity plural> list" ]
Set Variable [ $Total Records Label ; Value: "Total <Entity Plural>" ]
Set Variable [ $Add New Record Button Label ; Value: "Add New <Entity Name>" ]

Set Variable [ $No Record Found Icon ; Value: "<svg_path_or_url>" ]
Set Variable [ $No Record Found Message Title ; Value: "No <Entity Plural>" ]
Set Variable [ $No Record Found Message Body ; Value: "There are no <entity plural> set up." ]

Perform Script [ Specified: From list ; “+++ Display List HTML” ;
  Parameter:
    $SQL & ¶ &
    $SQL Condition & ¶ &
    $Column Headers & ¶ &
    $Column Widths & ¶ &
    $Status Column & ¶ &
    $Date Columns & ¶ &
    $Number Columns & ¶ &
    $Categorization Column & ¶ &
    $Searchable Columns & ¶ &
    $Add New Record Script Name & ¶ &
    $View Record Script Name & ¶ &
    $Search Field Placeholder & ¶ &
    $Total Records Label & ¶ &
    $Add New Record Button Label & ¶ &
    $No Record Found Icon & ¶ &
    $No Record Found Message Title & ¶ &
    $No Record Found Message Body
]

Set Variable [ $$Tab To Show ; Value: 1 ]
~~~

## 9.2 Legacy Renderer Template

~~~filemaker
# +++ <Entity Name> List Page (Legacy Renderer)

Set Variable [ $$App Section ; Value: "<Entity Name> List" ]

Set Variable [ $SQL ; Value:
"SELECT
  t1.ID,
  <field_expr_1>,
  <field_expr_2>
FROM <TableName> t1
<joins>
"
]

Set Variable [ $SQL Condition ; Value: 1 ]

Set Variable [ $Column Headers ; Value: "S/N,<Header 1>,<Header 2>,Actions" ]

Set Variable [ $Status Column ; Value: "" ]
Set Variable [ $Date Columns ; Value: "" ]
Set Variable [ $Number Columns ; Value: "" ]

Set Variable [ $Searchable Columns ; Value: "1,2" ]

Set Variable [ $Add New Record Script Name ; Value: "Add New <Entity Name>" ]
Set Variable [ $View Record Script Name ; Value: "+++ <Entity Name> Details Page" ]

Set Variable [ $Search Field Placeholder ; Value: "Search <entity plural> list" ]
Set Variable [ $Total Records Label ; Value: "Total <Entity Plural>" ]
Set Variable [ $Add New Record Button Label ; Value: "Add New <Entity Name>" ]

Set Variable [ $No Record Found Icon SVG Path ; Value: "<svg_path>" ]
Set Variable [ $No Record Found Message Title ; Value: "No <Entity Plural>" ]
Set Variable [ $No Record Found Message Body ; Value: "There are no <entity plural> set up." ]

Perform Script [ Specified: From list ; “+++ Display List HTML_” ;
  Parameter:
    $SQL & ¶ &
    $SQL Condition & ¶ &
    $Column Headers & ¶ &
    $Status Column & ¶ &
    $Date Columns & ¶ &
    $Number Columns & ¶ &
    $Searchable Columns & ¶ &
    $Add New Record Script Name & ¶ &
    $View Record Script Name & ¶ &
    $Search Field Placeholder & ¶ &
    $Total Records Label & ¶ &
    $Add New Record Button Label & ¶ &
    $No Record Found Icon SVG Path & ¶ &
    $No Record Found Message Title & ¶ &
    $No Record Found Message Body
]

Set Variable [ $$Tab To Show ; Value: 1 ]
~~~

---

# 10. Implementation Rules for Column Indexing (AI Agent Must Apply)

This section defines how to compute column indexes for:
- Status column
- Date columns
- Number columns
- Searchable columns
- Categorization column

## 10.1 Use 1-Based Indexing Aligned to Column Headers (Displayed Columns)
Indexes refer to positions in `$Column Headers` for:
- `$Status Column`
- `$Date Columns`
- `$Number Columns`
- `$Searchable Columns` (pending renderer confirmation)

Example:
`"S/N,Staff #,Full Name,Gender,Job Title,Department,Status,Actions"`

Indices:
1 = S/N  
2 = Staff #  
3 = Full Name  
4 = Gender  
5 = Job Title  
6 = Department  
7 = Status  
8 = Actions  

So:
- `$Status Column = 7`

Rule reinforcement:
- If status is used, it must be the last data column, so it should appear immediately before `Actions`.

## 10.2 Categorization Column Indexing (SQL Resultset Position, Hidden Allowed)
For categorization, the index may refer to the SQL resultset position (including hidden category fields).

Rule:
- If the list is categorized, include the category field in the SQL selected fields.
- Do not include the category in `$Column Headers`.
- Set `$Categorization Column` to the **position of the category field within the SQL selected fields**.

Example:
SQL selects:
1) `ID`
2) `Name`
3) `Role`
4) `Category`

Headers (category hidden):
- `"S/N,Name,Role,Actions"`

Categorization:
- `$Categorization Column = 4`

Important:
- This matches observed behavior in samples where `$Categorization Column` can appear to exceed the number of visible data columns. Final confirmation depends on how the renderer interprets index space. See Open Questions.

---

# 13. AI Agent Verification Checklist (Must Pass)

Before you consider the List Page script complete, verify all items:

## 13.1 SQL Checks
- [ ] First selected column is ID
- [ ] SQL returns all required display fields
- [ ] Aggregations have a valid GROUP BY
- [ ] Field names with spaces are quoted correctly
- [ ] Joins are correct and do not create row explosion
- [ ] If categorization is enabled: SQL includes category field in selected fields even if it is hidden from UI
- [ ] If status is displayed: status is positioned as the last data column before Actions

## 13.2 UI Columns Checks
- [ ] Column headers include `S/N` first and `Actions` last
- [ ] Header count equals widths count (if widths provided)
- [ ] If status is displayed: `Status` appears as the last header before `Actions`
- [ ] Status column index exists in headers (if provided)
- [ ] Date column indices exist in headers (if provided)
- [ ] Searchable columns indices exist in headers
- [ ] If categorization is enabled: category is NOT in headers, but categorization column index points to the correct SQL selected-field position (including hidden field)
- [ ] Column density looks readable on a 13-inch screen with a side menu (not cramped)

## 13.3 Script Routing Checks
- [ ] Add script name exists, or is intentionally empty
- [ ] View script name exists and is correct
- [ ] Search placeholder is meaningful
- [ ] Total label matches entity plural

## 13.4 Empty State Checks
- [ ] Icon is set
- [ ] Title is set
- [ ] Body is set

## 13.5 Renderer Signature Checks
- [ ] You are calling `+++ Display List HTML` with 17 parameters, or
- [ ] You are calling `+++ Display List HTML_` with 15 parameters
- [ ] The parameter order matches the selected renderer

---

# 14. Open Questions, Ambiguities, Contradictions (Needs Your Clarification)

These items must be clarified to make the AI training perfect. Please answer them and the spec will be updated.

## Q1: Which renderer is canonical?
Samples use both:
- `+++ Display List HTML`
- `+++ Display List HTML_`

Questions:
- Is `+++ Display List HTML_` deprecated?
- Should all list pages be migrated to `+++ Display List HTML`?
- If both are valid, what is the decision rule for choosing one?

## Q2: What is the exact meaning and usage of `$SQL Condition` inside the renderer?
Observed:
- Many lists set it to `1`
- InPatients sets it to values like `"On Admission"` and `"Discharged"`

Questions:
- Does the renderer append a WHERE clause using this value?
- Does the renderer do a Substitute into `$SQL` using this value?
- Is `$SQL Condition` used for filtering after query results are returned?
- What is the exact token or mechanism used by the renderer?

## Q3: How does the renderer interpret column indexes?
Observed:
- `$Status Column = 7` in Staff list aligns to headers including `S/N`
- `$Searchable Columns` includes `"1,2,3"` etc

Questions:
- Do indexes include `S/N` and `Actions`, or exclude them?
- Does the renderer internally shift indexes because ID is hidden?
- Is the index space based on displayed headers, or based on SQL result columns excluding ID?

## Q4: Categorization Column index space (SQL resultset vs headers)
Observed pattern you want:
- SQL selects category field
- Headers hide category field
- `$Categorization Column` points to the category field position in the SQL recordset

Questions:
- Confirm: is `$Categorization Column` based on SQL selected-field position (including hidden category field)?
- If yes: does the position count include the ID column as position 1?
- If no: what is the exact index-space rule?

## Q5: Empty state icon type (SVG path vs URL)
Observed:
- Most lists use `$No Record Found Icon SVG Path`
- Business Types uses `$No Record Found Icon URL`

Questions:
- Does `+++ Display List HTML` accept both SVG path and URL in the same parameter slot?
- If yes, how does it detect which one it is?
- If no, which one is the standard for the whole app?

## Q6: Column Widths required or optional for new renderer
Observed:
- Staff, Business Types, InPatients use widths
- Departments and Job Titles do not, and they also use legacy renderer

Questions:
- Is `$Column Widths` mandatory for `+++ Display List HTML`?
- If optional, what is the correct fallback behavior?

## Q7: Actions column behavior
Questions:
- Does the renderer always add Actions column UI automatically?
- Does it rely on the last header being literally `Actions`?
- What actions are included by default (View, Edit, Delete), and how are they configured?